### ISSUE TITLE
Implement clockodo requirements

### ISSUE THREAD

**Issue by jhnns** [peerigon/clockodo#50]
- [x] It should be possible to use cookie auth
- [x] It should be possible to configure the API endpoint -> #53
- [x] Refactor method params: Since we're using TypeScript, we don't need to split between required and optional parameters anymore. In a lot of instances, it's easier for the consumer to just use one method parameter (e.g. addEntry or editEntry).
- [ ] Add API errors
- [x] We should get rid of the lodash dependency, the bundle is currently too big see https://bundlephobia.com/result?p=clockodo@4.1.0 -> partially solved in #55 
- [x] We should not [rename query parameters](https://github.com/peerigon/clockodo/blob/master/src/internals/utilities/mapKeys.ts), only change the casing and remove special characters -> #53 
- [x] There should be a modern build without polyfills
- [x] Make axios-cache-adapter optional -> #55 
- [x] Harmonize entry type with Clockodo's internal entry type
- [x] Expose low-level get, post, put, delete with common error handling
- [ ] ~~Return response object (with statusCode, body and headers) instead just the body~~

**Comment by jhnns** [comment]
- Return response object (with statusCode, body and headers) instead just the body. This is necessary because sometimes there's important context information in HTTP headers which we should not hide. If possible, we should return a response object that looks like the one that is returned by fetch()

**Comment by jhnns** [comment]
- If an optional param is present in the object, but `undefined` it should not be sent to the server (that's the default for JSON.stringify() anyway). This makes it easier to work with the API since I can just call the API function with a possibly undefined param

**Comment by jhnns** [comment]
Most of it is done. The rest will be done on demand.
